const TelegramBot = require('node-telegram-bot-api');
const sqlite3 = require('sqlite3').verbose();
const axios = require('axios');
const express = require('express');

// ================= CONFIGURATION =================
const BOT_TOKEN = '8697527679:AAERZh3BIJBfKM2RaJMTm2NkvHICJLihKzU';
const SOCPANEL_URL = 'https://socpanel.com/privateApi';
const SOCPANEL_TOKEN = '2hKYpddKuEOCVPgM1Lgw8bXu5LZYD0d2LkBFSlzxHAsWeldoypZ2aUVcSIrQ';

const PORT = process.env.PORT || 3000;
const SMS_SECRET = 'NexerrSecretKey123';
// =================================================

const bot = new TelegramBot(BOT_TOKEN, { polling: true });
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const db = new sqlite3.Database('./nexerr_payments.db', (err) => {
    if (err) console.error("Database connection error:", err.message);
        else console.log("SQLite Database Connected Successfully!");
        });

        db.serialize(() => {
            db.run(`CREATE TABLE IF NOT EXISTS transactions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                            t_id TEXT UNIQUE,
                                    amount INTEGER,
                                            status TEXT DEFAULT 'Unused'
                                                )`);
                                                });

                                                const userSessions = {};

                                                app.get('/sms-webhook', (req, res) => {
                                                    const { t_id, amount, secret } = req.query;

                                                        if (secret !== SMS_SECRET) {
                                                                return res.status(403).json({ error: 'Unauthorized secret key' });
                                                                    }

                                                                        if (!t_id || !amount) {
                                                                                return res.status(400).json({ error: 't_id and amount are required' });
                                                                                    }

                                                                                        db.run(
                                                                                                `INSERT INTO transactions (t_id, amount, status) VALUES (?, ?, 'Unused')
                                                                                                         ON CONFLICT(t_id) DO NOTHING`,
                                                                                                                 [t_id.toString().trim(), parseInt(amount)],
                                                                                                                         function(err) {
                                                                                                                                     if (err) {
                                                                                                                                                     console.error('DB Insert Error:', err.message);
                                                                                                                                                                     return res.status(500).json({ error: 'Database error' });
                                                                                                                                                                                 }
                                                                                                                                                                                             console.log(`[SMS RECEIVED] T-ID: ${t_id} | Amount: Rs. ${amount}`);
                                                                                                                                                                                                         res.json({ success: true, message: 'Payment stored successfully' });
                                                                                                                                                                                                                 }
                                                                                                                                                                                                                     );
                                                                                                                                                                                                                     });

                                                                                                                                                                                                                     app.listen(PORT, () => {
                                                                                                                                                                                                                         console.log(`Nexerr Server is running on port ${PORT}`);
                                                                                                                                                                                                                         });

                                                                                                                                                                                                                         bot.onText(/\/start/, (msg) => {
                                                                                                                                                                                                                             const chatId = msg.chat.id;
                                                                                                                                                                                                                                 delete userSessions[chatId];
                                                                                                                                                                                                                                     bot.sendMessage(
                                                                                                                                                                                                                                             chatId,
                                                                                                                                                                                                                                                     "Welcome to Nexerr Auto Payment Bot! 🚀\n\nEasyPaisa/JazzCash payment karne ke baad, apni **11-digit Transaction ID (T-ID)** yahan enter karein:"
                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                         });

                                                                                                                                                                                                                                                         bot.on('message', async (msg) => {
                                                                                                                                                                                                                                                             const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                 const text = msg.text ? msg.text.trim() : '';

                                                                                                                                                                                                                                                                     if (text === '/start') return;

                                                                                                                                                                                                                                                                         const session = userSessions[chatId] || {};

                                                                                                                                                                                                                                                                             if (!session.step) {
                                                                                                                                                                                                                                                                                     if (text.length >= 10 && !isNaN(text)) {
                                                                                                                                                                                                                                                                                                 userSessions[chatId] = { step: 'WAITING_USERNAME', t_id: text };
                                                                                                                                                                                                                                                                                                             bot.sendMessage(
                                                                                                                                                                                                                                                                                                                             chatId,
                                                                                                                                                                                                                                                                                                                                             `✅ T-ID (${text}) receive ho gayi hai!\n\nAb apna Nexerr Panel ka **Username** (Login ID) type karke bhejein:`
                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                             bot.sendMessage(chatId, "❌ Invalid Transaction ID! Sahi 11-digit numeric T-ID enter karein:");
                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                             return;
                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                     if (session.step === 'WAITING_USERNAME') {
                                                                                                                                                                                                                                                                                                                                                                                                             const username = text;
                                                                                                                                                                                                                                                                                                                                                                                                                     const t_id = session.t_id;

                                                                                                                                                                                                                                                                                                                                                                                                                             bot.sendMessage(chatId, "⏳ Payment verify ki ja rahi hai, please wait...");

                                                                                                                                                                                                                                                                                                                                                                                                                                     db.get(`SELECT * FROM transactions WHERE t_id = ? AND status = 'Unused'`, [t_id], async (err, row) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error('DB Query Error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 bot.sendMessage(chatId, "❌ System error! Operational issue.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!row) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         bot.sendMessage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             chatId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "❌ Transaction ID match nahi hui ya pehle se claim ho chuki hai!\n\nCheck karein ke aapne sahi T-ID daali hai ya payment aane mein thora time lag raha hai."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const response = await axios.get(`${SOCPANEL_URL}/incrementUserBalance`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             params: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     token: SOCPANEL_TOKEN,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             login: username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     amount: row.amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (response.data && response.data.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             db.run(`UPDATE transactions SET status = 'Used' WHERE t_id = ?`, [t_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     bot.sendMessage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             chatId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `🎉 *Payment Successful!*\n\nRs. ${row.amount} successfully user *${username}* ke account mein add kar diye gaye hain!\n\nNexerr use karne ka shukriya! ❤️`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     bot.sendMessage(chatId, `❌ Username '${username}' nahi mila ya Socpanel API issue hai. Please live support se contact karein.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error('Socpanel API Error:', error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 bot.sendMessage(chatId, "❌ Socpanel server response error. Support team se rabta karein.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.log("Nexerr Auto Payment Bot is live & running...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     