const TelegramBot = require('node-telegram-bot-api');
const sqlite3 = require('sqlite3').verbose();
const axios = require('axios');
const express = require('express');

// ================= CONFIGURATION =================
const BOT_TOKEN = '8697527679:AAERZh3BIJBfKM2RaJMTm2NkvHICJLihKzU';
const SOCPANEL_URL = 'https://socpanel.com/privateApi';
const SOCPANEL_TOKEN = '2hKYpddKuEOCVPgM1Lgw8bXu5LZYD0d2LkBFSlzxHAsWeldoypZ2aUVcSIrQ';

const PORT = process.env.PORT || 3000;
const SMS_SECRET = 'NexerrSecretKey123';
// =================================================

const bot = new TelegramBot(BOT_TOKEN, { polling: true });
const app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const db = new sqlite3.Database('./nexerr_payments.db', (err) => {
    if (err) console.error("Database connection error:", err.message);
        else console.log("SQLite Database Connected Successfully!");
        });

        db.serialize(() => {
            db.run(`CREATE TABLE IF NOT EXISTS transactions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                            t_id TEXT UNIQUE,
                                    amount INTEGER,
                                            status TEXT DEFAULT 'Unused'
                                                )`);
                                                });

                                                const userSessions = {};

                                                app.get('/sms-webhook', (req, res) => {
                                                    const { msg, secret } = req.query;

                                                        if (secret !== SMS_SECRET) {
                                                                return res.status(403).json({ error: 'Unauthorized secret key' });
                                                                    }

                                                                        if (!msg) {
                                                                                return res.status(400).json({ error: 'msg parameter is required' });
                                                                                    }

                                                                                        // Smart SMS extraction for EasyPaisa / JazzCash
                                                                                            const tidMatch = msg.match(/\b(\d{11,12})\b/); 
                                                                                                const amountMatch = msg.match(/(?:Rs\.?|PKR)\s*([\d,]+)/i);

                                                                                                    if (!tidMatch || !amountMatch) {
                                                                                                            console.log("[SMS IGNORED] Could not extract T-ID or Amount from message:", msg);
                                                                                                                    return res.status(400).json({ error: 'Regex could not match TID or Amount' });
                                                                                                                        }

                                                                                                                            const t_id = tidMatch[1];
                                                                                                                                const amount = parseInt(amountMatch[1].replace(/,/g, ''));

                                                                                                                                    db.run(
                                                                                                                                            `INSERT INTO transactions (t_id, amount, status) VALUES (?, ?, 'Unused')
                                                                                                                                                     ON CONFLICT(t_id) DO NOTHING`,
                                                                                                                                                             [t_id.toString().trim(), amount],
                                                                                                                                                                     function(err) {
                                                                                                                                                                                 if (err) {
                                                                                                                                                                                                 console.error('DB Insert Error:', err.message);
                                                                                                                                                                                                                 return res.status(500).json({ error: 'Database processing error' });
                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                         console.log(`[WEBHOOK SUCCESS] T-ID: ${t_id} | Amount: Rs. ${amount}`);
                                                                                                                                                                                                                                                     res.json({ success: true, message: 'Transaction logged successfully' });
                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                 );
                                                                                                                                                                                                                                                                 });

                                                                                                                                                                                                                                                                 app.listen(PORT, () => {
                                                                                                                                                                                                                                                                     console.log(`Nexerr Payment Webhook running on port ${PORT}`);
                                                                                                                                                                                                                                                                     });

                                                                                                                                                                                                                                                                     bot.onText(/\/start/, (msg) => {
                                                                                                                                                                                                                                                                         const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                             delete userSessions[chatId];
                                                                                                                                                                                                                                                                                 bot.sendMessage(
                                                                                                                                                                                                                                                                                         chatId,
                                                                                                                                                                                                                                                                                                 "Welcome to the **Nexerr Auto Payment Bot**! 🚀\n\nTo automatically fund your account via EasyPaisa or JazzCash, please enter your **11-digit Transaction ID (T-ID)** below:",
                                                                                                                                                                                                                                                                                                         { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                             bot.on('message', async (msg) => {
                                                                                                                                                                                                                                                                                                                 const chatId = msg.chat.id;
                                                                                                                                                                                                                                                                                                                     const text = msg.text ? msg.text.trim() : '';

                                                                                                                                                                                                                                                                                                                         if (text === '/start') return;

                                                                                                                                                                                                                                                                                                                             const session = userSessions[chatId] || {};

                                                                                                                                                                                                                                                                                                                                 if (!session.step) {
                                                                                                                                                                                                                                                                                                                                         if (text.length >= 10 && !isNaN(text)) {
                                                                                                                                                                                                                                                                                                                                                     userSessions[chatId] = { step: 'WAITING_USERNAME', t_id: text };
                                                                                                                                                                                                                                                                                                                                                                 bot.sendMessage(
                                                                                                                                                                                                                                                                                                                                                                                 chatId,
                                                                                                                                                                                                                                                                                                                                                                                                 `✅ Transaction ID **(${text})** received successfully.\n\nPlease enter your Nexerr Panel **Username** (Login ID) to proceed:`,
                                                                                                                                                                                                                                                                                                                                                                                                                 { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                                                     } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                 bot.sendMessage(chatId, "❌ **Invalid Input.**\nPlease enter a valid 11-digit numeric Transaction ID (T-ID).", { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (session.step === 'WAITING_USERNAME') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const username = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const t_id = session.t_id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 bot.sendMessage(chatId, "⏳ Verifying your payment, please wait...");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         db.get(`SELECT * FROM transactions WHERE t_id = ? AND status = 'Unused'`, [t_id], async (err, row) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.error('DB Query Error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     bot.sendMessage(chatId, "❌ **System Error:** Unable to process the request at this time. Please contact support.", { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!row) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             bot.sendMessage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 chatId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "❌ **Verification Failed!**\n\nThe Transaction ID was not found or has already been claimed. Please ensure you entered the correct T-ID.\n\n*Note: It may take up to 2-3 minutes for recent payments to sync with our system.*",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const response = await axios.get(`${SOCPANEL_URL}/incrementUserBalance`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     params: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             token: SOCPANEL_TOKEN,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     login: username,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             amount: row.amount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (response.data && response.data.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     db.run(`UPDATE transactions SET status = 'Used' WHERE t_id = ?`, [t_id]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             bot.sendMessage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     chatId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             `🎉 *Payment Successful!*\n\nAn amount of **Rs. ${row.amount}** has been successfully added to the account: *${username}*.\n\nThank you for choosing Nexerr! ❤️`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     { parse_mode: 'Markdown' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             bot.sendMessage(chatId, `❌ **Account Error:** Username '${username}' not found. Please verify your login ID or contact live support.`, { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         console.error('Socpanel API Error:', error.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         bot.sendMessage(chatId, "❌ **API Error:** Server is currently unresponsive. Please contact our support team.", { parse_mode: 'Markdown' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 delete userSessions[chatId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.log("Nexerr Auto Payment Bot is live & running...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             